{
 "title": "New dashboard",
 "time": { "from": "now-2y", "to": "now" },
 "panels": [
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT prediction_drift, \"timestamp\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Share of missing values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT share_missing_values, \"timestamp\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT num_drifted_colunms, \"timestamp\" FROM dummy_metrics LIMIT 50 "
    }
   ]
  }
 ]
}